In [4]:
# Import libraries
import numpy as np

# Numpy
Main object is the homogeneous multidimensional array

Numpy's array class is called **ndarray**. Aka. alais **array** 
* Note: `numpy.array` is not equal to Standard Python Library `array.array`

ndarray.ndim. 
- the number of axes (dimensions) of the array.

ndarray.shape. 
- the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.

ndarray.size. 
- the total number of elements of the array. This is equal to the product of the elements of shape.

ndarray.dtype. 
- an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.

ndarray.itemsize. 
- the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.

ndarray.data. 
- the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities

In [16]:
py_array = [[1., 0., 0], [0., 1., 2.]]
np_array = np.array([[1., 0., 0], [0., 1., 2.]])

In [25]:

np_array.data

In [27]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
a.ndim

2

In [33]:
c = np.arange(120).reshape(2, 3, 4, 5)
c

array([[[[  0,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14],
         [ 15,  16,  17,  18,  19]],

        [[ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34],
         [ 35,  36,  37,  38,  39]],

        [[ 40,  41,  42,  43,  44],
         [ 45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59]]],


       [[[ 60,  61,  62,  63,  64],
         [ 65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74],
         [ 75,  76,  77,  78,  79]],

        [[ 80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94],
         [ 95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104],
         [105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119]]]])

In [43]:
type(c)

numpy.ndarray

## What is Scalars, Vectors, Matrics, Tensors

1. Scalars, Vectors, Matrices, Tensors
   Think of these as different "containers" for numbers:  
   Scalar: Just a single number (like 5 or 3.14)  
   ndim = 0, shape ()  
   Vector: A list of numbers (like [1, 2, 3])
 
   ndim = 1, shape (3,)
   Think: a single row or column of numbers
   Matrix: A table of numbers (rows and columns)
 
   ndim = 2, shape (3, 4) means 3 rows, 4 columns
   Think: a spreadsheet
   Tensor: Multi-dimensional array (3D, 4D, etc.)
 
   ndim = 3+, shape (2, 3, 4) and beyond
   Think: a cube of numbers, or multiple matrices stacked  together

```
# Examples in NumPy
scalar = np.array(5)              # ndim = 0
vector = np.array([1, 2, 3])      # ndim = 1, shape (3,)
matrix = np.array([[1, 2],        # ndim = 2, shape (2, 3)
                   [3, 4],
                   [5, 6]])
tensor = np.arange(24).reshape(2, 3, 4)  # ndim = 3, shape (2, 3, 4)
```




2. Matrix Multiplication Rules
   Key rule: The inner dimensions must match!  
   For A @ B to work:  
   If A is (m, n) and B is (p, q)  
   Then n must equal p  
   Result will be (m, q)  

In [47]:
A = np.arange(6).reshape(2,3)
B = np.arange(7,13).reshape(3,2)
print(f"A is {A}")
print(f"B is {B}")

A is [[0 1 2]
 [3 4 5]]
B is [[ 7  8]
 [ 9 10]
 [11 12]]


In [52]:
C = A @ B # Result : shape (2,2)
C.shape

(2, 2)

3. Dot Product  
The dot product is like asking: "How much do these two vectors point in the same direction?"

In [53]:
a = np.arange(3)
b = np.arange(4,7)
print(f"a is {a}")
print(f"b is {b}")

a is [0 1 2]
b is [4 5 6]


In [57]:
dot_product = np.dot(a,b)
dot_at_product = a @ b
print(f"dot product {dot_product}")
print(f"@ product {dot_at_product}")
dot_product.shape

dot product 17
@ product 17


()

4. Transpose  
Flip rows and columns!

In [64]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])  # shape (2, 3)

A_T = A.T  # shape (3, 2)
# [[1, 4],
#  [2, 5],
#  [3, 6]]
A_T

array([[1, 4],
       [2, 5],
       [3, 6]])

5. Identity Matrix  
The "do nothing" matrix - like multiplying by 1.

In [ ]:
I = np.eye(3)  # 3x3 identity matrix
# [[1, 0, 0],
#  [0, 1, 0],
#  [0, 0, 1]]

A = np.array([[2, 3],
              [4, 5]])

print(A @ np.eye(2))  # Returns A unchanged
# A @ I = I @ A = A

[[2. 3.]
 [4. 5.]]


6. Norms (L1, L2)  
   Norms measure the "size" or "length" of a vector. Like measuring how far you are from the origin.

   L1 Norm (Manhattan distance)  
   Sum of absolute values - like walking on a grid (can  only go horizontal/vertical).

In [66]:
v = np.array([3, -4, 5])
l1_norm = np.linalg.norm(v, ord=1)  # = |3| + |-4| + |5| = 12
# Or manually: np.sum(np.abs(v))
print(f"Manhattan distacne {l1_norm}")

Manhattan distacne 12.0


   L2 Norm (Euclidean distance)  
   Square root of sum of squares - straight-line distance.

In [68]:
euclid_dis = np.array([3, -4])
l2_norm = np.linalg.norm(euclid_dis)
print(f"Euclidian Distance is {l2_norm}")

Euclidian Distance is 5.0


L1: City block distance (taxi cab)  
L2: "As the crow flies" distance (straight line)

In [69]:
# Comparison
v = np.array([3, 4])
print(f"L1 norm: {np.linalg.norm(v, ord=1)}")  # 7
print(f"L2 norm: {np.linalg.norm(v, ord=2)}")  # 5

L1 norm: 7.0
L2 norm: 5.0
