In [2]:
# import lib
import numpy as np

In [16]:
A = np.array([[1,2,3],[4,5,6]])
A.shape

(2, 3)

In [17]:

print("Matrix:\n", A)
print("Transpose:\n", A.T)
print("Dot product of row vectors:\n", np.dot(A[0], A[1]))

Matrix:
 [[1 2 3]
 [4 5 6]]
Transpose:
 [[1 4]
 [2 5]
 [3 6]]
Dot product of row vectors:
 32


Write a short note inside the notebook:  
- What is a matrix?
- What is transpose?
- Why are these operations important for deep learning?

### What is a matrix
Matrix is a grid of numbers in rows and columns, such as table or spreadsheet.

### What is transpose
Transpose is flip/rotating the matrix into 90 degrees.

### Why are these operations important from deep learning?
1. Neural networks are matrix operations
2. Batch processing
3. Transpose for dimension matching
4. Backpropagation requires transpose